version: '3.8'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
    privileged: true
    shm_size: 2g

  app:
    build: .
    restart: always
    depends_on:
      - db
      - chrome
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - .:/app
#    command: tail -f /dev/null